up

diff --git a/.github/workflows/package-deploy.yml b/.github/workflows/package-deploy.yml
--- a/.github/workflows/package-deploy.yml
+++ b/.github/workflows/package-deploy.yml
@@ -1,10 +1,6 @@
 name: Deploy package to nuget
 
 on:
-  push:
-    branches:
-      - "feature/init"
-      - "main"
   workflow_dispatch:
 
 env:
@@ -35,6 +31,18 @@ jobs:
     needs: run-tests
     runs-on: ubuntu-latest
     steps:
+      - name: Check Main Branch
+        run: |
+          if [[ "${{ github.ref_name }}" != "main" ]]; then
+            echo "This workflow can only be triggered on the 'main' branch."
+            exit 1
+          fi
+      - name: Check Repository Owner
+        run: |
+          if [[ "${{ github.actor }}" != "${{ github.repository_owner }}" ]]; then
+            echo "Unauthorized: Only the repository owner (${ github.repository_owner }) can trigger this workflow."
+            exit 1
+          fi
       - uses: actions/checkout@v4
       - uses: actions/setup-dotnet@v4
         with:
