finalize

diff --git a/.github/workflows/package-deploy.yml b/.github/workflows/package-deploy.yml
--- a/.github/workflows/package-deploy.yml
+++ b/.github/workflows/package-deploy.yml
@@ -24,24 +24,24 @@ permissions:
   contents: write
 
 jobs:
-#  job-verification:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Check Main Branch
-#        run: |
-#           if [[ "${{ github.ref_name }}" != "main" ]]; then
-#             echo "This workflow can only be triggered on the 'main' branch."
-#             exit 1
-#           fi
-#      - name: Check Repository Owner
-#        run: |
-#          if [[ "${{ github.actor }}" != "${{ github.repository_owner }}" ]]; then
-#            echo "Unauthorized: Only the repository owner (${ github.repository_owner }) can trigger this workflow."
-#            exit 1
-#          fi
+  job-verification:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check Main Branch
+        run: |
+           if [[ "${{ github.ref_name }}" != "main" ]]; then
+             echo "This workflow can only be triggered on the 'main' branch."
+             exit 1
+           fi
+      - name: Check Repository Owner
+        run: |
+          if [[ "${{ github.actor }}" != "${{ github.repository_owner }}" ]]; then
+            echo "Unauthorized: Only the repository owner (${ github.repository_owner }) can trigger this workflow."
+            exit 1
+          fi
 
   job-tests:
-    # needs: job-verification
+    needs: job-verification
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -57,7 +57,7 @@ jobs:
         run: dotnet test $TESTS_PROJ_PATH -c Release
 
   AR_NetExt_Awaiter:
-    ##needs: job-tests
+    needs: job-tests
     uses: ./.github/workflows/deploy-package-flow.yml
     if: ${{ inputs.package_name == 'AR.NetExt.Awaiter' }}
     secrets:
@@ -66,7 +66,7 @@ jobs:
       project_path: './src/AR.NetExt.Awaiter/AR.NetExt.Awaiter.csproj'
 
   AR_NetExt_DateTime:
-    #needs: job-tests
+    needs: job-tests
     uses: ./.github/workflows/deploy-package-flow.yml
     if: ${{ inputs.package_name == 'AR.NetExt.DateTime' }}
     secrets:
@@ -75,7 +75,7 @@ jobs:
       project_path: './src/AR.NetExt.DateTime/AR.NetExt.DateTime.csproj'
 
   AR_NetExt_MayBe:
-    #needs: job-tests
+    needs: job-tests
     uses: ./.github/workflows/deploy-package-flow.yml
     if: ${{ inputs.package_name == 'AR.NetExt.MayBe' }}
     secrets:
@@ -84,7 +84,7 @@ jobs:
       project_path: './src/AR.NetExt.MayBe/AR.NetExt.MayBe.csproj'
 
   AR_NetExt_Models:
-    #needs: job-tests
+    needs: job-tests
     uses: ./.github/workflows/deploy-package-flow.yml
     if: ${{ inputs.package_name == 'AR.NetExt.Models' }}
     secrets:
@@ -94,7 +94,7 @@ jobs:
       
 
   AR_NetExt_Require:
-    #needs: job-tests
+    needs: job-tests
     uses: ./.github/workflows/deploy-package-flow.yml
     if: ${{ inputs.package_name == 'AR.NetExt.Require' }}
     secrets:
@@ -104,7 +104,7 @@ jobs:
       
 
   AR_NetExt_Strings:
-    #needs: job-tests
+    needs: job-tests
     uses: ./.github/workflows/deploy-package-flow.yml
     if: ${{ inputs.package_name == 'AR.NetExt.Strings' }}
     secrets:
@@ -113,7 +113,7 @@ jobs:
       project_path: './src/AR.NetExt.Strings/AR.NetExt.Strings.csproj'
   
   AR_NetExt_Utils:
-    #needs: job-tests
+    needs: job-tests
     uses: ./.github/workflows/deploy-package-flow.yml
     if: ${{ inputs.package_name == 'AR.NetExt.Utils' }}
     secrets:
